name: 'Setup Bun Workspace'
description: 'Setup Bun, restore caches, and install dependencies'

inputs:
  bun-version:
    description: 'Bun version to install'
    required: false
    default: '1.3.1'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
      shell: bash

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
      shell: bash

    - name: Cache Turborepo
      uses: rharkor/caching-for-turbo@v2.3.2
      shell: bash

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
